// Generated by github.com/yoyo-project/yoyo

package repositories

import (
	"database/sql"
	"fmt"
	
	"github.com/yoyo-project/yoyo/example/mysql/yoyo/repositories/nullable"
)

type Person struct { 
	Id uint32
	Name string
	Nickname string
	FavoriteColor nullable.String
	Age float64

	// Reference Fields
	CityId uint32
	
	// For tracking persistence
	persisted *Person
}

type Persons struct {
	// If we're not in a transaction, then Person saves memory by wrapping a *sql.Rows to scan from the connection
	// buffer on-demand.
	// This uses less application memory but more connections to the DBMS.
	rs *sql.Rows

	// If we are in a transaction, then Person reads the entire result set to memory to clear the buffer and allow
	// other queries to run on the goroutine.
	// This uses more application memory but fewer connections to the DBMS.
	i  int
	es []Person
}

// Next is intended to feel familiar to the Next method of sql.Rows. In fact, when not in a transaction,
// it uses the sql.Rows Next method internally.
func (es *Persons) Next() bool {
	if es.rs != nil {
		// not in a transaction
		return es.rs.Next()
	} else {
		// in a transaction
		es.i++
		return es.i < len(es.es)
	}
}

// Scan is intended to feel familiar to the Scan method of sql.Rows. In fact, when not in a transaction,
// it uses the sql.Rows Scan method internally.
func (es *Persons) Scan(e *Person) (err error) {
	if e == nil {
		return fmt.Errorf("in Persons.Scan: passed a nil entity")
	}

	// scan from the rows if NOT IN a transaction
	if es.rs != nil {
		return es.scan(e)
	}

	// load an entity from memory if IN a transaction
	return es.load(e)
}

// scan wraps the Scan method of sql.Rows, only used when not in a connection to minimize memory usage
func (es *Persons) scan(e *Person) (err error) {
	err = es.rs.Scan(&e.Id, &e.Name, &e.Nickname, &e.FavoriteColor, &e.Age, &e.CityId)
	persisted := *e
	e.persisted = &persisted
	return err
}

// load pulls a result from memory, only used if in a transaction to avoid connection contention
func (es *Persons) load(e *Person) (err error) {
	if es.i >= len(es.es) || es.i < 0 {
		return fmt.Errorf("in Persons.point: out of range")
	}
	*e = es.es[es.i]
	persisted := *e
	e.persisted = &persisted
	return nil
}