// Generated by github.com/yoyo-project/yoyo

package repositories

import (
	"database/sql"
	"fmt"
	
)

type NoPkTable struct { 
	Col int32
	Col2 int32
	// For tracking persistence
	persisted *NoPkTable
}

type NoPkTables struct {
	// If we're not in a transaction, then NoPkTable saves memory by wrapping a *sql.Rows to scan from the connection
	// buffer on-demand.
	// This uses less application memory but more connections to the DBMS.
	rs *sql.Rows

	// If we are in a transaction, then NoPkTable reads the entire result set to memory to clear the buffer and allow
	// other queries to run on the goroutine.
	// This uses more application memory but fewer connections to the DBMS.
	i  int
	es []NoPkTable
}

// Next is intended to feel familiar to the Next method of sql.Rows. In fact, when not in a transaction,
// it uses the sql.Rows Next method internally.
func (es *NoPkTables) Next() bool {
	if es.rs != nil {
		// not in a transaction
		return es.rs.Next()
	} else {
		// in a transaction
		es.i++
		return es.i < len(es.es)
	}
}

// Scan is intended to feel familiar to the Scan method of sql.Rows. In fact, when not in a transaction,
// it uses the sql.Rows Scan method internally.
func (es *NoPkTables) Scan(e *NoPkTable) (err error) {
	if e == nil {
		return fmt.Errorf("in NoPkTables.Scan: passed a nil entity")
	}

	// scan from the rows if NOT IN a transaction
	if es.rs != nil {
		return es.scan(e)
	}

	// load an entity from memory if IN a transaction
	return es.load(e)
}

// scan wraps the Scan method of sql.Rows, only used when not in a connection to minimize memory usage
func (es *NoPkTables) scan(e *NoPkTable) (err error) {
	err = es.rs.Scan(&e.Col, &e.Col2)
	persisted := *e
	e.persisted = &persisted
	return err
}

// load pulls a result from memory, only used if in a transaction to avoid connection contention
func (es *NoPkTables) load(e *NoPkTable) (err error) {
	if es.i >= len(es.es) || es.i < 0 {
		return fmt.Errorf("in NoPkTables.point: out of range")
	}
	*e = es.es[es.i]
	persisted := *e
	e.persisted = &persisted
	return nil
}